# Generated by Django 3.1 on 2020-08-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='watch_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user_watch_list',
            field=models.BooleanField(default=False),
        ),
    ]
