# Generated by Django 3.1 on 2020-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating', '0002_auto_20200823_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
