# Generated by Django 3.1 on 2020-08-06 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, help_text='format : DD-MM-YYYY', null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('mobile', models.CharField(default=None, max_length=20, null=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
